name: Build and Test Spring Boot Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build jar with Maven
      run: mvn package --file product/pom.xml

    - name: Create docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/product-banquito:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-banquito:latest

    - name: Connect to EC2 instance using SSH recipe
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop product-banquito || true
          docker rm product-banquito || true
          docker run --rm -d --name product-banquito -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/product-banquito:latest
